// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
 

#nullable disable

namespace SB.Model
{
    public partial class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool? IsActive { get; set; }
    }
}