// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

#nullable disable

namespace SB.Model
{
    public partial class Inventory
    {

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Complated { get; set; }
        public bool IsActive { get; set; }
        public DateTime OnDate { get; set; }
    }

}
