// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
 
#nullable disable

namespace SB.Model
{
    public partial class UserMaster
    {
        
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string HasPassword { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? OnDate { get; set; }
    }

     

}