// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SB.Repository.TableModel
{
    public partial class tblUserMaster
    {
        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string FullName { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(18)]
        public string Password { get; set; }
        public string HasPassword { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? OnDate { get; set; }
    }
}