// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SB.Repository.TableModel;

#nullable disable

namespace SB.Repository.Database
{
    public partial class DbshopbridgeContext : DbContext
    {
        public DbshopbridgeContext()
        {
        }

        public DbshopbridgeContext(DbContextOptions<DbshopbridgeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tblInventory> tblInventory { get; set; }
        public virtual DbSet<tblUserMaster> tblUserMaster { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                   //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=TWOX-PC-07;Initial Catalog=dbShopBridge;Persist Security Info=True;User ID=sa;Password=pass");
                base.OnConfiguring(optionsBuilder);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Icelandic_100_CI_AS");

            modelBuilder.Entity<tblInventory>(entity =>
            {
                entity.Property(e => e.Complated).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}